export const REQUEST = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    LOADING: 'LOADING',
}

export const MAP_ACTION = {
    SET_MIN_RANGE: 'SET_MIN_RANGE',
    SET_MAX_RANGE: 'SET_MAX_RANGE',
    SET_POLYLINE_OPACITY: 'SET_POLYLINE_OPACITY'
}
